### ISSUE TITLE
Unknown error code - 300

### ISSUE THREAD

**Issue by mark-veenstra** [hasscontrol/hasscontrol#22]
Hi,

Thanks for the HassControl add-on. But I am having trouble setting it up. I am using the Hass Nabu Casa Cloud URL which is configured in the ConnectIQ as the host also added a group as described in the setup instructions and not using scenes and not using long-lived access token. My config looks like:

```
host: 'https://ABCDEFG.ui.nabu.casa/'
Long-lived access token (optional): ''
Scenes: (scene1,scene2,scene3): ''
Group: 'group.garmin'
```
Within Home Assistant I added the group to `groups.yaml` as follows:
```yaml
garmin:
  name: Garmin
  entities:
    - light.ikea_lamp_test
    - switch.sonoff_zigbee
```
Once I open the widget on the watch I need to login which I did and login went successfull. But refresh entities throws the error `Unknown error code - 300`
