### ISSUE TITLE
Add guide to documentation on how to add custom entities that are not directly supported by HassControl

### ISSUE THREAD

**Issue by aahlborg** [hasscontrol/hasscontrol#45]
I requested support for additional entity types but I realized that some of them could be implemented as custom entities in Home Assistant. It could be useful for the users of HassControl to have a short guide in the documentation about how certain types of entities could be supported. For example, switches need to be defined as lights before they can be added to a controllable group and a vacuum cleaner could be implemented as a template switch.

#### Switch group

Lights, switches and light groups are supported but not groups of switches. To add switches to a light group you first need to define a light switch. This example shows how to add three switches as a light group:

````yaml
light:
  - platform: switch
    name: Tree lights
    entity_id: switch.tradfri_outlet_1
  - platform: switch
    name: Balcony lights
    entity_id: switch.tradfri_outlet_2
  - platform: switch
    name: Window lights
    entity_id: switch.tradfri_outlet_3
  - platform: group
    name: Christmas lights
    entities:
      - light.tree_lights
      - light.balcony_lights
      - light.window_lights
````

They can then be added to the Garmin group as lights.christmas_lights:

````yaml
group:
  garmin:
    name: Garmin
    entities:
      - light.christmas_lights
````

#### Template switch

Many devices are not supported directly but their behaviour can be modelled as a simple on/off switch. Here is an example of a vacuum cleaner being implemented as a template switch:

````yaml
switch:
  - platform: template
    switches:
      roborock_control:
        friendly_name: Roborock Control
        value_template: "{{ is_state('vacuum.roborock', 'cleaning') or is_state('vacuum.roborock', 'returning') }}"
        turn_on:
          service: vacuum.start
          target:
            entity_id: vacuum.roborock
        turn_off:
          service: vacuum.pause
          target:
            entity_id: vacuum.roborock
````

**Comment by Sturmkater** [comment]
Hi aahlborg,
I tried your approach, but still get an error. I added all my light switches to the configuration.yaml and then invented new light ids:
````
light:
  - platform: switch
    name: Stubelivingcolor
    entity_id: switch.stube_livingcolor
  - platform: switch
    name: Stubeliecht
    entity_id: switch.licht_wohnzimmer
  - platform: switch
    name: Bueroliecht
    entity_id: switch.licht_office
  - platform: switch
    name: Esszimmerliecht
    entity_id: switch.licht_esszimmer
  - platform: switch
    name: Badliecht
    entity_id: switch.licht_bad
  - platform: group
    name: Husliecht
    entities:
      - light.stube_livingcolor
      - light.wohnzimmer
      - light.office
	  - light.esszimmer
	  - light.bad
````

But I still get an error for line - light.esszimmer

Any Ideas what I'm doing wrong?
