### ISSUE TITLE
group provoke error

### ISSUE THREAD

**Issue by Sturmkater** [hasscontrol/hasscontrol#51]
Hi, I tried several ways to get my group set up in the manner as your description, but always getting an error wile restarting the core.

Errormessage: 

> Failed to restart Home AssistantCore
> The system cannot restart because the configuration is not valid: Invalid config for [group]: [garmin] is an invalid option for [group]. Check: group->group->group->garmin. (See /config/configuration.yaml, line 15).

my groups.yml file:

```
group:
  garmin:
    name: Garmin
    entities:
      - script.film
      - light.licht_bad
      - script.1635763537270
```
